apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tagmind-ingress
  namespace: tagmind
spec:
  ingressClassName: nginx
  rules:
    - host: tg.tagmind.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tg-gateway
                port:
                  number: 80
    - host: orchestrator.tagmind.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: orchestrator-api
                port:
                  number: 80
    - host: retriever.tagmind.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web-retriever
                port:
                  number: 80
    - host: llm.tagmind.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: llm-gateway
                port:
                  number: 80
