apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tagmind-ingress
  namespace: tagmind
spec:
  ingressClassName: nginx
  rules:
    - host: tagmind.local
      http:
        paths:
          - path: /tg
            pathType: Prefix
            backend:
              service:
                name: tg-gateway
                port:
                  number: 80

          - path: /orchestrator
            pathType: Prefix
            backend:
              service:
                name: orchestrator-api
                port:
                  number: 80

          - path: /retriever
            pathType: Prefix
            backend:
              service:
                name: web-retriever
                port:
                  number: 80

          - path: /llm
            pathType: Prefix
            backend:
              service:
                name: llm-gateway
                port:
                  number: 80
